#cloud-config
users:
  - name: admin
    gecos: Bastion Admin
    shell: /bin/bash
    groups: sudo
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh-authorized-keys:
      - ${file("/opt/stack/.ssh/id_rsa.pub")} 

package_update: true
package_upgrade: true
packages:
  - net-tools
  - htop
  - curl
  - vim

runcmd:
  - echo "Bastion ready" > /etc/motd
