# 1. 사용자 계정 생성
users:
  - name: admin
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ${file("/opt/stack/.ssh/id_rsa.pub")}

# 2. 패키지 설치
packages:
  - snort
  - filebeat
  - curl
  - net-tools

# 3. Filebeat 설정 (Logstash로 전송)
write_files:
  - path: /etc/filebeat/filebeat.yml
    content: |
      filebeat.inputs:
        - type: log
          enabled: true
          paths:
            - /var/log/snort/snort.alert.fast
      output.logstash:
        hosts: ["10.10.10.200:5044"]
    owner: root:root
    permissions: '0644'

# 4. Snort 설정 (기본 설정 사용 가능)
runcmd:
  - systemctl enable filebeat
  - systemctl start filebeat
