#cloud-config

users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${file("/opt/stack/.ssh/id_rsa.pub")}

package_update: true
package_upgrade: true
packages:
  - iptables
  - iptables-persistent
  - curl
  - gnupg
  - apt-transport-https
  - net-tools

runcmd:
  - |
    # 기본 iptables 정책 설정
    iptables -P INPUT DROP
    iptables -P FORWARD DROP
    iptables -P OUTPUT ACCEPT
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables -A INPUT -p tcp --dport 22 -j ACCEPT

    # iptables 저장
    netfilter-persistent save

    # Filebeat 설치
    curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-7.x.list
    apt update && apt install -y filebeat

    # Filebeat 설정 파일 덮어쓰기
    cat <<EOF > /etc/filebeat/filebeat.yml
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/kern.log
          - /var/log/syslog

    output.logstash:
      hosts: ["10.10.10.200:5044"]
    EOF

    systemctl enable filebeat
    systemctl start filebeat
